settings:
  title: 'Theo dõi sever'
  url: 'https://status.hmodapk.comcom' # used for Slack & Discord messages
  logo: logo-hmodapk.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  # configurable texts across the status page
  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: 'Some checks failed'

# list of monitors
monitors:
  - id: hmodapk # unique identifier
    name: Hmodapk.comcom
    description: 'Tình trạng sever của website: Hmodapk.com' # default=empty
    url: 'https://hmodapk.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # should the titles be links to the service, default=true
